//
// Resource header file generated by CTRPP tool, contains STRINGID definition.
//
#define IDS_test_00027         27
#define IDS_test_00025         25
#define IDS_test_00026         26
#define IDS_test_00023         23
#define IDS_test_00021         21
#define IDS_test_00022         22
#define IDS_test_00019         19
#define IDS_test_00017         17
#define IDS_test_00018         18
#define IDS_test_00015         15
#define IDS_test_00013         13
#define IDS_test_00014         14
#define IDS_test_00011         11
#define IDS_test_00009          9
#define IDS_test_00010         10
#define IDS_test_00007          7
#define IDS_test_00005          5
#define IDS_test_00006          6
#define IDS_test_00003          3
#define IDS_test_00001          1
#define IDS_test_00002          2

